<?php

namespace TrainBundle\Repository;

/**
 * GareDeserviRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GareDeserviRepository extends \Doctrine\ORM\EntityRepository
{
}
