<?php

namespace TrainBundle\Repository;

/**
 * GareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GareRepository extends \Doctrine\ORM\EntityRepository
{
}
