<?php

namespace TrainBundle\Repository;

/**
 * SiegeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiegeRepository extends \Doctrine\ORM\EntityRepository
{
}
