<?php

namespace TrainBundle\Repository;

/**
 * TrainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrainRepository extends \Doctrine\ORM\EntityRepository
{
}
