<?php

namespace TrainBundle\Repository;

/**
 * TrajetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrajetRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByGareDAndGareADepart($gareDepart, $gareArrive, $jour1, $jour2)
    {
        $qb = $this->createQueryBuilder('t');

        $qb->leftJoin('t.gareDepart', 'gD')
            ->leftJoin('t.gareArrive', 'gA')
            ->leftJoin('gA.ville', 'vA')
            ->leftJoin('gD.ville', 'vD')
            ->where('vD.city = :gareDepart')
                ->setParameter('gareDepart', $gareDepart)
            ->andWhere('vA.city = :gareArrive')
                ->setParameter('gareArrive', $gareArrive)
            ->andWhere('t.heureDepart BETWEEN :jour1 and :jour2')
            ->setParameter('jour1', $jour1)
            ->setParameter('jour2', $jour2)
            ->orderBy('t.heureDepart', 'DESC')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

    public function findByGareDAndGareAArrive($gareDepart, $gareArrive, $jour1, $jour2)
    {
        $qb = $this->createQueryBuilder('t');

        $qb->leftJoin('t.gareDepart', 'gD')
            ->leftJoin('t.gareArrive', 'gA')
            ->leftJoin('gA.ville', 'vA')
            ->leftJoin('gD.ville', 'vD')
            ->where('vD.city = :gareDepart')
            ->setParameter('gareDepart', $gareDepart)
            ->andWhere('vA.city = :gareArrive')
            ->setParameter('gareArrive', $gareArrive)
            ->andWhere('t.heureArrive BETWEEN :jour1 and :jour2')
            ->setParameter('jour1', $jour1)
            ->setParameter('jour2', $jour2)
            ->orderBy('t.heureArrive', 'DESC')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
