<?php

namespace TrainBundle\Repository;

/**
 * TrajetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrajetRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByGareDAndGareA($gareDepart, $gareArrive, $heureDepart, $heureArrive)
    {
        $qb = $this->createQueryBuilder('t');

        $qb->where('t.gareDepart = :gareDepart')
            ->setParameter('gareDepart', $gareDepart)
            ->andWhere('t.gareArrive = :gareArrive')
            ->setParameter('gareArrive', $gareArrive)
            ->andWhere('t.heureDepart = :heureDepart')
            ->setParameter('heureDepart', $heureDepart)
            ->andWhere('t.heureArrive = :heureArrive')
            ->setParameter('heureArrive', $heureArrive)
            ->orderBy('t.heureDepart', 'DESC')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
