<?php

namespace TrainBundle\Repository;

/**
 * WagonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WagonRepository extends \Doctrine\ORM\EntityRepository
{
}
